import {
  RegionInfo,
  OSImage,
  ComputePlan,
  Instance,
  DatabaseCluster,
  Volume,
  S3Bucket,
  Firewall,
  VPC,
  LoadBalancer,
  FloatingIP,
  Domain,
  ClientTenant,
  MarginConfig,
  Transaction,
  Invoice,
  OperationalAlert,
} from "../types/cloud";

export const REGIONS: RegionInfo[] = [
  { id: "nyc1", name: "New York 1", flag: "🇺🇸", country: "US East", city: "New York", pingMs: 18 },
  { id: "sfo3", name: "San Francisco 3", flag: "🇺🇸", country: "US West", city: "San Francisco", pingMs: 34 },
  { id: "fra1", name: "Frankfurt 1", flag: "🇩🇪", country: "EU Central", city: "Frankfurt", pingMs: 82 },
  { id: "lon1", name: "London 1", flag: "🇬🇧", country: "EU West", city: "London", pingMs: 76 },
  { id: "ams3", name: "Amsterdam 3", flag: "🇳🇱", country: "EU North", city: "Amsterdam", pingMs: 80 },
  { id: "sgp1", name: "Singapore 1", flag: "🇸🇬", country: "AP South", city: "Singapore", pingMs: 185 },
  { id: "tyo1", name: "Tokyo 1", flag: "🇯🇵", country: "AP East", city: "Tokyo", pingMs: 142 },
  { id: "blr1", name: "Bangalore 1", flag: "🇮🇳", country: "AP South", city: "Bangalore", pingMs: 195 },
];

export const OS_IMAGES: OSImage[] = [
  { id: "ubuntu-24-04", name: "Ubuntu 24.04 LTS", version: "Noble Numbat", family: "ubuntu", kernel: "Linux 6.8" },
  { id: "ubuntu-22-04", name: "Ubuntu 22.04 LTS", version: "Jammy Jellyfish", family: "ubuntu", kernel: "Linux 5.15" },
  { id: "debian-12", name: "Debian 12", version: "Bookworm", family: "debian", kernel: "Linux 6.1" },
  { id: "alpine-320", name: "Alpine Linux 3.20", version: "Edge Minimal", family: "alpine", kernel: "Linux 6.6" },
  { id: "fedora-40", name: "Fedora Cloud 40", version: "Server Base", family: "fedora", kernel: "Linux 6.8" },
  { id: "arch-linux", name: "Arch Linux", version: "Rolling Release", family: "arch", kernel: "Linux 6.9" },
  { id: "rocky-9", name: "Rocky Linux 9", version: "Enterprise Blue", family: "rhel", kernel: "Linux 5.14" },
];

export const COMPUTE_PLANS: ComputePlan[] = [
  { id: "plan-micro", name: "Standard Micro 1G", tier: "basic", vcpu: 1, ramGb: 1, diskGb: 25, transferTb: 1, wholesaleMonthly: 4.0, retailMonthly: 6.0, hourlyRetail: 0.009 },
  { id: "plan-basic", name: "Standard Basic 2G", tier: "basic", vcpu: 1, ramGb: 2, diskGb: 50, transferTb: 2, wholesaleMonthly: 8.0, retailMonthly: 12.0, hourlyRetail: 0.018 },
  { id: "plan-std-4g", name: "General Purpose 4G", tier: "general", vcpu: 2, ramGb: 4, diskGb: 80, transferTb: 3, wholesaleMonthly: 16.0, retailMonthly: 24.0, hourlyRetail: 0.036 },
  { id: "plan-std-8g", name: "General Purpose 8G", tier: "general", vcpu: 4, ramGb: 8, diskGb: 160, transferTb: 4, wholesaleMonthly: 32.0, retailMonthly: 48.0, hourlyRetail: 0.072 },
  { id: "plan-cpu-16g", name: "Compute Optimized 16G", tier: "cpu-optimized", vcpu: 8, ramGb: 16, diskGb: 240, transferTb: 5, wholesaleMonthly: 56.0, retailMonthly: 84.0, hourlyRetail: 0.125 },
  { id: "plan-mem-32g", name: "Memory Optimized 32G", tier: "memory-optimized", vcpu: 8, ramGb: 32, diskGb: 320, transferTb: 6, wholesaleMonthly: 88.0, retailMonthly: 132.0, hourlyRetail: 0.196 },
  { id: "plan-gpu-a5000", name: "AI Accelerator A5000 24G", tier: "gpu-ai", vcpu: 16, ramGb: 64, diskGb: 500, transferTb: 10, wholesaleMonthly: 260.0, retailMonthly: 390.0, hourlyRetail: 0.58 },
];

export const INITIAL_INSTANCES: Instance[] = [
  {
    id: "inst-prod-api-01",
    name: "prod-api-cluster-01",
    region: "nyc1",
    image: "ubuntu-24-04",
    planId: "plan-std-8g",
    plan: COMPUTE_PLANS[3],
    status: "active",
    ipv4: "142.93.18.102",
    privateIpv4: "10.108.0.12",
    currentCpu: 34,
    currentRamPercent: 58,
    uptimeSeconds: 1428500,
    tags: ["production", "api", "k8s-worker"],
    clientId: "client-1",
    createdAt: "2026-06-12",
  },
  {
    id: "inst-db-primary",
    name: "postgres-primary-sfo",
    region: "sfo3",
    image: "debian-12",
    planId: "plan-mem-32g",
    plan: COMPUTE_PLANS[5],
    status: "active",
    ipv4: "159.203.44.89",
    privateIpv4: "10.108.16.4",
    currentCpu: 22,
    currentRamPercent: 74,
    uptimeSeconds: 2894100,
    tags: ["database", "primary", "nvme"],
    clientId: "client-2",
    createdAt: "2026-05-18",
  },
  {
    id: "inst-web-gateway",
    name: "edge-nginx-proxy",
    region: "fra1",
    image: "alpine-320",
    planId: "plan-basic",
    plan: COMPUTE_PLANS[1],
    status: "active",
    ipv4: "46.101.99.14",
    privateIpv4: "10.108.32.2",
    currentCpu: 11,
    currentRamPercent: 28,
    uptimeSeconds: 981200,
    tags: ["gateway", "edge", "ssl"],
    clientId: "client-1",
    createdAt: "2026-07-01",
  },
  {
    id: "inst-gpu-inference",
    name: "deepseek-v3-infer",
    region: "lon1",
    image: "ubuntu-24-04",
    planId: "plan-gpu-a5000",
    plan: COMPUTE_PLANS[6],
    status: "active",
    ipv4: "178.62.204.55",
    privateIpv4: "10.108.48.9",
    currentCpu: 78,
    currentRamPercent: 86,
    uptimeSeconds: 341000,
    tags: ["ai", "vllm", "cuda-12"],
    clientId: "client-3",
    createdAt: "2026-08-14",
  },
  {
    id: "inst-dev-sandbox",
    name: "staging-dev-worker",
    region: "ams3",
    image: "fedora-40",
    planId: "plan-std-4g",
    plan: COMPUTE_PLANS[2],
    status: "off",
    ipv4: "188.166.12.80",
    privateIpv4: "10.108.64.15",
    currentCpu: 0,
    currentRamPercent: 0,
    uptimeSeconds: 0,
    tags: ["staging", "sandbox"],
    clientId: "client-2",
    createdAt: "2026-08-20",
  },
];

export const INITIAL_DATABASES: DatabaseCluster[] = [
  {
    id: "db-pg-cluster",
    name: "aurora-pg-prod",
    engine: "postgresql",
    version: "16.3",
    region: "nyc1",
    status: "online",
    nodesCount: 2,
    haEnabled: true,
    diskAllocatedGb: 200,
    diskUsedGb: 68,
    ramGb: 16,
    vcpu: 4,
    port: 5432,
    host: "pg-aurora.internal.cloudnova.net",
    defaultDb: "cloudnova_prod",
    adminUser: "nova_admin",
    adminPasswordReveal: "nV9#mK8$zQ2!vL90xR",
    connectionUri: "postgresql://nova_admin:nV9#mK8$zQ2!vL90xR@pg-aurora.internal.cloudnova.net:5432/cloudnova_prod?sslmode=require",
    wholesaleMonthly: 90.0,
    retailMonthly: 135.0,
    users: [
      { username: "nova_admin", role: "admin", createdAt: "2026-05-10" },
      { username: "app_worker", role: "read_write", createdAt: "2026-05-12" },
      { username: "bi_analytics", role: "read_only", createdAt: "2026-06-01" },
    ],
    schemas: ["cloudnova_prod", "analytics", "auditing"],
    pools: [
      {
        id: "pool-1",
        name: "api-trans-pool",
        database: "cloudnova_prod",
        user: "app_worker",
        mode: "transaction",
        size: 50,
        connectionUri: "postgresql://app_worker:***@pg-aurora.internal.cloudnova.net:6432/cloudnova_prod",
      },
    ],
    backups: [
      { id: "bak-today", createdAt: "Today, 03:00 UTC", sizeMb: 2450, status: "completed" },
      { id: "bak-yesterday", createdAt: "Yesterday, 03:00 UTC", sizeMb: 2410, status: "completed" },
    ],
    replicas: [
      { id: "rep-fra", name: "pg-replica-fra1", region: "fra1", status: "online", lagMs: 42 },
    ],
    trustedSources: ["10.108.0.0/16", "142.93.18.102"],
    createdAt: "2026-05-10",
  },
  {
    id: "db-redis-cache",
    name: "redis-fast-cache",
    engine: "redis",
    version: "7.2",
    region: "sfo3",
    status: "online",
    nodesCount: 1,
    haEnabled: false,
    diskAllocatedGb: 20,
    diskUsedGb: 4.8,
    ramGb: 8,
    vcpu: 2,
    port: 6379,
    host: "redis.internal.cloudnova.net",
    defaultDb: "0",
    adminUser: "default",
    adminPasswordReveal: "rD9!kP3#wQ7xZ",
    connectionUri: "rediss://default:rD9!kP3#wQ7xZ@redis.internal.cloudnova.net:6379",
    wholesaleMonthly: 35.0,
    retailMonthly: 52.0,
    users: [{ username: "default", role: "admin", createdAt: "2026-06-04" }],
    schemas: ["db0", "db1"],
    pools: [],
    backups: [{ id: "bak-redis-1", createdAt: "Today, 04:00 UTC", sizeMb: 120, status: "completed" }],
    replicas: [],
    trustedSources: ["10.108.0.0/16"],
    createdAt: "2026-06-04",
  },
];

export const INITIAL_VOLUMES: Volume[] = [
  {
    id: "vol-db-nvme",
    name: "vol-postgres-data",
    region: "sfo3",
    sizeGb: 500,
    iops: 7500,
    attachedToInstanceId: "inst-db-primary",
    filesystem: "ext4",
    wholesaleMonthly: 40.0,
    retailMonthly: 60.0,
    createdAt: "2026-05-18",
  },
  {
    id: "vol-app-media",
    name: "vol-media-assets",
    region: "nyc1",
    sizeGb: 250,
    iops: 3750,
    attachedToInstanceId: "inst-prod-api-01",
    filesystem: "xfs",
    wholesaleMonthly: 20.0,
    retailMonthly: 30.0,
    createdAt: "2026-06-15",
  },
  {
    id: "vol-unattached-spare",
    name: "vol-cold-archive-01",
    region: "fra1",
    sizeGb: 1000,
    iops: 10000,
    attachedToInstanceId: null,
    filesystem: "ext4",
    wholesaleMonthly: 80.0,
    retailMonthly: 120.0,
    createdAt: "2026-07-22",
  },
];

export const INITIAL_BUCKETS: S3Bucket[] = [
  {
    id: "bucket-static-assets",
    name: "cloudnova-static-cdn",
    region: "nyc1",
    acl: "public-read",
    storageClass: "STANDARD",
    cdnActive: true,
    totalSizeBytes: 18450000000, // ~18.4 GB
    objectCount: 1420,
    wholesaleMonthly: 4.5,
    retailMonthly: 7.2,
    endpoint: "https://cloudnova-static-cdn.s3.nyc1.cloudnova.io",
    objects: [
      { key: "app/bundles/v2.4.1.tar.gz", sizeBytes: 42100000, lastModified: "2026-09-02", contentType: "application/gzip" },
      { key: "assets/logo-vector.svg", sizeBytes: 18400, lastModified: "2026-08-10", contentType: "image/svg+xml" },
      { key: "assets/hero-mockup.webp", sizeBytes: 480200, lastModified: "2026-08-12", contentType: "image/webp" },
      { key: "firmware/agent-latest.bin", sizeBytes: 12400000, lastModified: "2026-09-04", contentType: "application/octet-stream" },
    ],
    createdAt: "2026-05-15",
  },
  {
    id: "bucket-vault-backups",
    name: "secure-db-backups-vault",
    region: "fra1",
    acl: "private",
    storageClass: "INFREQUENT",
    cdnActive: false,
    totalSizeBytes: 148200000000, // ~148.2 GB
    objectCount: 38,
    wholesaleMonthly: 18.0,
    retailMonthly: 28.8,
    endpoint: "https://secure-db-backups-vault.s3.fra1.cloudnova.io",
    objects: [
      { key: "postgres/daily-2026-09-05.sql.zst", sizeBytes: 2480000000, lastModified: "2026-09-05", contentType: "application/zstd" },
      { key: "postgres/daily-2026-09-04.sql.zst", sizeBytes: 2420000000, lastModified: "2026-09-04", contentType: "application/zstd" },
    ],
    createdAt: "2026-05-20",
  },
];

export const INITIAL_FIREWALLS: Firewall[] = [
  {
    id: "fw-web-gateway",
    name: "web-gateway-shield",
    attachedInstanceIds: ["inst-prod-api-01", "inst-web-gateway"],
    rules: [
      { id: "r1", type: "inbound", protocol: "tcp", ports: "80,443", sources: ["0.0.0.0/0", "::/0"], action: "accept", label: "HTTP & HTTPS Web Traffic" },
      { id: "r2", type: "inbound", protocol: "tcp", ports: "22", sources: ["142.93.0.0/16"], action: "accept", label: "SSH Bastion Whitelist" },
      { id: "r3", type: "outbound", protocol: "all", ports: "all", sources: ["0.0.0.0/0", "::/0"], action: "accept", label: "All Outbound Egress" },
    ],
    createdAt: "2026-05-12",
  },
  {
    id: "fw-db-internal",
    name: "db-isolated-group",
    attachedInstanceIds: ["inst-db-primary"],
    rules: [
      { id: "r4", type: "inbound", protocol: "tcp", ports: "5432", sources: ["10.108.0.0/16"], action: "accept", label: "VPC Internal Postgres" },
      { id: "r5", type: "inbound", protocol: "tcp", ports: "22", sources: ["10.108.0.12"], action: "accept", label: "SSH from API Node Only" },
      { id: "r6", type: "outbound", protocol: "tcp", ports: "443,53", sources: ["0.0.0.0/0"], action: "accept", label: "DNS & S3 Backup Outbound" },
    ],
    createdAt: "2026-05-18",
  },
];

export const INITIAL_VPCS: VPC[] = [
  { id: "vpc-us-east", name: "vpc-us-east-prod", region: "nyc1", cidr: "10.108.0.0/20", isDefault: true, connectedInstancesCount: 2, createdAt: "2026-05-01" },
  { id: "vpc-us-west", name: "vpc-us-west-data", region: "sfo3", cidr: "10.108.16.0/20", isDefault: false, connectedInstancesCount: 1, createdAt: "2026-05-18" },
  { id: "vpc-eu-central", name: "vpc-eu-frankfurt", region: "fra1", cidr: "10.108.32.0/20", isDefault: true, connectedInstancesCount: 1, createdAt: "2026-06-01" },
];

export const INITIAL_LOAD_BALANCERS: LoadBalancer[] = [
  {
    id: "lb-api-ingress",
    name: "api-gateway-lb",
    region: "nyc1",
    ip: "142.93.18.200",
    protocol: "HTTPS",
    port: 443,
    algorithm: "round_robin",
    targetInstanceIds: ["inst-prod-api-01"],
    healthCheckPath: "/healthz",
    sslEnabled: true,
    createdAt: "2026-06-12",
  },
];

export const INITIAL_FLOATING_IPS: FloatingIP[] = [
  { id: "fip-1", ip: "142.93.18.254", region: "nyc1", assignedInstanceId: "inst-prod-api-01", createdAt: "2026-06-12" },
  { id: "fip-2", ip: "159.203.44.100", region: "sfo3", assignedInstanceId: null, createdAt: "2026-07-01" },
];

export const INITIAL_DOMAINS: Domain[] = [
  {
    id: "dom-1",
    name: "cloudnova.io",
    tld: ".io",
    status: "active",
    whoisPrivacy: true,
    autoRenew: true,
    dnssec: true,
    sslActive: true,
    expiresAt: "2027-05-10",
    wholesaleAnnual: 32.0,
    retailAnnual: 48.0,
    linkedResourceId: "inst-prod-api-01",
    records: [
      { id: "rec-1", type: "A", name: "@", value: "142.93.18.102", ttl: 300 },
      { id: "rec-2", type: "CNAME", name: "api", value: "cloudnova.io", ttl: 300 },
      { id: "rec-3", type: "CNAME", name: "static", value: "cloudnova-static-cdn.s3.nyc1.cloudnova.io", ttl: 300 },
      { id: "rec-4", type: "TXT", name: "@", value: "v=spf1 include:_spf.google.com ~all", ttl: 3600 },
    ],
  },
  {
    id: "dom-2",
    name: "hyperstack.cloud",
    tld: ".cloud",
    status: "active",
    whoisPrivacy: true,
    autoRenew: true,
    dnssec: false,
    sslActive: true,
    expiresAt: "2027-02-18",
    wholesaleAnnual: 14.0,
    retailAnnual: 22.0,
    linkedResourceId: "bucket-static-assets",
    records: [
      { id: "rec-5", type: "CNAME", name: "@", value: "cloudnova-static-cdn.s3.nyc1.cloudnova.io", ttl: 300 },
    ],
  },
];

export const INITIAL_CLIENTS: ClientTenant[] = [
  {
    id: "client-1",
    name: "Acme Cloud Infrastructure",
    email: "ops@acmecorp.com",
    company: "Acme Corp Ltd.",
    balance: 1420.5,
    creditLimit: 5000,
    status: "active",
    customMarkupPercent: 30,
    activeResourcesCount: 4,
    monthlySpend: 218.4,
    createdAt: "2026-04-10",
  },
  {
    id: "client-2",
    name: "ByteWorks Data Systems",
    email: "dev@byteworks.io",
    company: "ByteWorks LLC",
    balance: 890.0,
    creditLimit: 3500,
    status: "active",
    customMarkupPercent: 40,
    activeResourcesCount: 3,
    monthlySpend: 164.0,
    createdAt: "2026-05-02",
  },
  {
    id: "client-3",
    name: "SynthAI Neural Labs",
    email: "billing@synthai.ai",
    company: "SynthAI Labs Inc.",
    balance: 3400.0,
    creditLimit: 12000,
    status: "active",
    customMarkupPercent: 50,
    activeResourcesCount: 2,
    monthlySpend: 442.0,
    createdAt: "2026-07-15",
  },
];

export const INITIAL_MARGIN_CONFIG: MarginConfig = {
  globalMarkupPercent: 35,
  computeMarkupPercent: 40,
  domainsMarkupPercent: 45,
  volumesMarkupPercent: 50,
  s3MarkupPercent: 60,
  currency: "USD",
};

export const INITIAL_TRANSACTIONS: Transaction[] = [
  { id: "tx-1092", date: "Sep 6, 12:30", type: "deposit", description: "Prepaid Wallet Top-up (Stripe •••• 4242)", amount: 250.0, status: "completed", resourceCategory: "wallet" },
  { id: "tx-1091", date: "Sep 6, 00:00", type: "usage_charge", description: "Hourly Droplets & Storage Metering", amount: -14.82, status: "completed", resourceCategory: "compute" },
  { id: "tx-1090", date: "Sep 5, 00:00", type: "usage_charge", description: "Hourly Droplets & Storage Metering", amount: -14.80, status: "completed", resourceCategory: "compute" },
  { id: "tx-1089", date: "Sep 2, 16:20", type: "domain_purchase", description: "Domain Registration (hyperstack.cloud)", amount: -14.0, status: "completed", resourceCategory: "domains" },
  { id: "tx-1088", date: "Sep 1, 09:15", type: "deposit", description: "USDC Crypto Instant Settlement", amount: 500.0, status: "completed", resourceCategory: "wallet" },
];

export const INITIAL_INVOICES: Invoice[] = [
  { id: "inv-2026-08", period: "Aug 1 - Aug 31, 2026", dueDate: "Sep 1, 2026", totalWholesale: 482.5, totalRetail: 724.8, netProfit: 242.3, status: "paid", pdfUrl: "#" },
  { id: "inv-2026-07", period: "Jul 1 - Jul 31, 2026", dueDate: "Aug 1, 2026", totalWholesale: 410.0, totalRetail: 615.0, netProfit: 205.0, status: "paid", pdfUrl: "#" },
  { id: "inv-2026-06", period: "Jun 1 - Jun 30, 2026", dueDate: "Jul 1, 2026", totalWholesale: 340.2, totalRetail: 510.3, netProfit: 170.1, status: "paid", pdfUrl: "#" },
];

export const INITIAL_ALERTS: OperationalAlert[] = [
  { id: "alt-1", title: "Automated PITR Backup Succeeded", message: "Cluster aurora-pg-prod completed incremental snapshot.", severity: "success", timestamp: "10m ago", read: false },
  { id: "alt-2", title: "DDoS Mitigation Triggered", message: "Edge scrubbed 4.2 Gbps UDP flood targeting IP 142.93.18.102.", severity: "info", timestamp: "1h ago", read: false },
  { id: "alt-3", title: "Prepaid Wallet Healthy", message: "Prepaid balance is sufficient for 48+ days of current burn.", severity: "info", timestamp: "1d ago", read: true },
];
